const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('yuexin', {
  getState: () => ipcRenderer.invoke('state:get'),
  onState: (callback) => ipcRenderer.on('state:changed', (_event, state) => callback(state)),
  onTab: (callback) => ipcRenderer.on('panel:tab', (_event, tab) => callback(tab)),
  onReminder: (callback) => ipcRenderer.on('reminder:fired', (_event, title) => callback(title)),
  onChatDelta: (callback) => ipcRenderer.on('chat:delta', (_event, text) => callback(text)),
  onAction: (callback) => ipcRenderer.on('pet:action', (_event, id) => callback(id)),
  onFeed: (callback) => ipcRenderer.on('pet:feed', (_event, image) => callback(image)),
  onFeedingMenu: (callback) => ipcRenderer.on('feeding:openMenu', () => callback()),
  feed: (foodId) => ipcRenderer.invoke('feeding:feed', foodId),
  finishFeeding: () => ipcRenderer.send('feeding:finished'),
  setFeedingImage: (actionId) => ipcRenderer.invoke('feeding:setImage', actionId),
  importFeedingImage: () => ipcRenderer.invoke('feeding:importImage'),
  setFeedingDuration: (seconds) => ipcRenderer.invoke('feeding:duration', seconds),
  onHover: (callback) => ipcRenderer.on('pet:hover', (_event, hover) => callback(hover)),
  setPetDragging: (dragging) => ipcRenderer.send('pet:dragging', dragging),
  openPanel: (tab) => ipcRenderer.invoke('panel:open', tab),
  getPetPosition: () => ipcRenderer.invoke('pet:getPosition'),
  setPetPosition: (x, y) => ipcRenderer.send('pet:setPosition', x, y),
  addReminder: (input) => ipcRenderer.invoke('reminder:add', input),
  toggleReminder: (id) => ipcRenderer.invoke('reminder:toggle', id),
  deleteReminder: (id) => ipcRenderer.invoke('reminder:delete', id),
  refreshLimits: () => ipcRenderer.invoke('limits:refresh'),
  connectAccount: () => ipcRenderer.invoke('account:connect'),
  selectCodexProgram: () => ipcRenderer.invoke('account:selectCli'),
  setAlwaysOnTop: (enabled) => ipcRenderer.invoke('settings:top', enabled),
  setAutoStart: (enabled) => ipcRenderer.invoke('settings:autoStart', enabled),
  setPetScale: (value) => ipcRenderer.invoke('settings:scale', value),
  setIdleAnimations: (enabled) => ipcRenderer.invoke('settings:idle', enabled),
  setRandomInterval: (seconds) => ipcRenderer.invoke('settings:interval', seconds),
  playAction: (id) => ipcRenderer.invoke('pet:action', id),
  importAction: (duration) => ipcRenderer.invoke('action:import', duration),
  removeAction: (id) => ipcRenderer.invoke('action:remove', id),
  updateAction: (id, update) => ipcRenderer.invoke('action:update', id, update),
  sendChat: (message) => ipcRenderer.invoke('chat:send', message),
  openChatGPT: () => ipcRenderer.invoke('chatgpt:openUsage'),
});
